recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LfN7AUAAAAAAHEg9ZPeXcevEIXSZcrDXnsa1w7Y"
	privateKey = "6LfN7AUAAAAAAFn6mKLuUURA-qYmIRL4JLTPTpA1"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}